#/bin/bash

IMAGE_INFO=$(cat version.txt)
IMAGE_INFO=(${IMAGE_INFO//:/ })
IMAGE_NAME=${IMAGE_INFO[0]}
IMAGE_VERSION=${IMAGE_INFO[1]}
IMAGE_VERSION_TOKENS=(${IMAGE_VERSION//./ })
IMAGE_VERSION_MAJOR=${IMAGE_VERSION_TOKENS[0]}
IMAGE_VERSION_MINOR=${IMAGE_VERSION_TOKENS[1]}
IMAGE_VERSION_BUGFIX=${IMAGE_VERSION_TOKENS[2]}

echo "[$IMAGE_NAME] Building version $IMAGE_VERSION ..."
docker build -t "$IMAGE_NAME":latest -t "$IMAGE_NAME":$IMAGE_VERSION_MAJOR -t "$IMAGE_NAME":$IMAGE_VERSION_MAJOR.$IMAGE_VERSION_MINOR -t "$IMAGE_NAME":$IMAGE_VERSION_MAJOR.$IMAGE_VERSION_MINOR.$IMAGE_VERSION_BUGFIX .

if [ "$1" = "-p" ]; then
    echo "[$IMAGE_NAME] to hub.docker.com ..."
    docker push "$IMAGE_NAME"
fi
